Repository getgauge/gauge.org, pull requests merged in 2018-10, with the labels that each got.

#109 taiko-launch poster and change in banner style
  source/assets/stylesheets/_font.scss
  source/assets/stylesheets/layout/_banner.scss
  source/assets/vendor/fonts/urw-geometric/ URWGeometric-Bold.otf
  source/index.html.erb
Labels: ready, review

#110 Banner update
  source/assets/stylesheets/layout/_banner.scss
Labels: cla-signed, ready, review

#111 Banner update
  source/assets/stylesheets/layout/_banner.scss
Labels: cla-signed, ready, review

#114 minor fine tuning
  source/assets/stylesheets/layout/_banner.scss
Labels: cla-signed, ready, review

#115 blog post and banner heading minor fixes
  source/assets/stylesheets/_blog.scss
  source/assets/stylesheets/layout/_banner.scss
Labels: cla-signed, ready, review

#117 completed fine tuning of getting started page
  source/assets/javascripts/site.js
  source/assets/stylesheets/_getting-started.scss
  source/assets/stylesheets/components/_sidebar.scss
  source/get_started/index.html.erb
  source/partials/_page_controls.html.erb
  source/partials/get-started/_create-project.html.erb
  source/partials/get-started/_create-specification.html.erb
  source/partials/get-started/_generate-report.html.erb
  source/partials/get-started/_next-steps.html.erb
  source/partials/get-started/_quick-install.html.erb
Labels: cla-signed, ready, review

#122 Update _create-project.html.erb
  source/partials/get-started/_create-project.html.erb
Labels: cla-signed, ready

#123 Update _create-specification.html.erb
  source/partials/get-started/_create-specification.html.erb
Labels: cla-signed, ready

#124 Update _we-start.html.erb
  source/partials/get-started/_we-start.html.erb
Labels: cla-signed, ready

#125 Update 2018-10-23-taiko-beta-reliable-browser-automation.html.markdow…
  source/posts/2018-10-23-taiko-beta-reliable-browser-automation.html.markdown.erb
Labels: cla-signed, ready

#127 changed the page arch of get started page.
  source/assets/stylesheets/components/_sidebar.scss
  source/get_started/create-project.html.erb
  source/get_started/create-specification.html.erb
  source/get_started/generate-report.html.erb
  source/get_started/next-steps.html.erb
  source/get_started/quick-install.html.erb
  source/get_started/we-start.html.erb
  source/partials/get-started/_create-project.html.erb
  source/partials/get-started/_create-specification.html.erb
  source/partials/get-started/_generate-report.html.erb
  source/partials/get-started/_next-steps.html.erb
  source/partials/get-started/_quick-install.html.erb
  source/partials/get-started/_we-start.html.erb
Labels: cla-signed, ready, review

#129 bug fix with links
  source/assets/javascripts/site.js
Labels: ready, review
